'use client'
import "./globals.css";
import Layout from "@/components/layout/Layout";

import { AppProps } from 'next/app';
import { Inter ,Jost} from '@next/font/google';
import { useEffect, useState } from "react";
import Loader from "@/components/common/Loader";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
const jost = Jost({ subsets: ['latin'] });

export default function RootLayout({ children }){
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const timer = setTimeout(() => {
      setLoading(false);
    }, 1000);

    return () => clearTimeout(timer); 
  }, []);

 
  return (
    <html lang="en">
      <body className={jost.className}>
        <Layout>
        {loading ? <Loader /> : children}
        </Layout>
      </body>
    </html>
  );
}
